#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

[ -n "$CI" ] && exit 0

PATH="/usr/local/bin:$PATH"

# Format and submit code according to lintstagedrc.js configuration
npm exec lint-staged --allow-empty $1
